server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/algo
spring.datasource.username=postgres
spring.datasource.password=1010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable Scheduling
spring.main.allow-bean-definition-overriding=true
